name: Actions after commit
run-name: Running appropriate tests after committing changes
on: push
jobs:
  test_artifacts:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - run: echo ${{runner.os}}
      - run: pip install -r requirements.txt
        if: runner.os == 'Windows'
      - run: pip install -r requirements_ubuntu.txt
        if: runner.os == 'Linux'
      - run: pip install .
      - run: python -m pytest tests/test_biotsavart.py
      - run: python src/biotsavart_modes/biotsavart/biotsavart.py
      - run: python -m pytest tests/test_fourier.py
      - run: python src/biotsavart_modes/plotting/plot_modes.py
      - name: Archive output of biotsavart and fourier calculation
        uses: actions/upload-artifact@v4
        with:
          name: output-folder
          path: src/biotsavart_modes/output/field_modes.png

# execute with flag --artifact-server-path /tmp/artifacts